# Predict Students Dropout - Get Raw Data

##### Predict_Students_Dropout_Get_Raw_Data_01.ipynb


This notebook is responsible for acquiring the raw data for the "Predict Students' Dropout and Academic Success" project. The data is fetched from an external source, inspected for initial understanding, and saved in a local CSV file for further processing.

## Steps
1. **Load the Data**: Fetch the dataset from the website (archive.ics.uci.edu).
2. **Initial Inspection**: Display the first few rows and the data summary to understand its structure and contents.
3. **Save Raw Data**: Store the raw data in a CSV file in data folder for future use in other notebooks.

In [3]:
# The '!' allows us to run shell commands in the notebook
# command installs the Python packages listed in the requirements.txt file
#!pip install -r requirements.txt

In [4]:
#Import required packages

from ucimlrepo import fetch_ucirepo

import os
import pandas as pd
import pprint

In [5]:
# Fetch dataset from source ucirepo with id=697
try:
    predict_students_dropout = fetch_ucirepo(id=697)
    print("Dataset fetched successfully.")
except Exception as e:
    print(f"Error fetching dataset: {e}")
    raise

# Data (as pandas dataframes)
try:
    X = predict_students_dropout.data.features
    y = predict_students_dropout.data.targets
    print("Data extracted successfully.")
except Exception as e:
    print(f"Error extracting data: {e}")
    raise

Dataset fetched successfully.
Data extracted successfully.

In [7]:
# Display information about DataFrame X
X.info()  # Provides summary of DataFrame X (columns, non-null values, data types, memory usage)

# Display information about Series or DataFrame y
y.info()  # Provides summary of y (columns, non-null values, data types, memory usage)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 36 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Marital Status                                  4424 non-null   int64
 1   Application mode                                4424 non-null   int64
 2   Application order                               4424 non-null   int64
 3   Course                                          4424 non-null   int64
 4   Daytime/evening attendance                      4424 non-null   int64
 5   Previous qualification                          4424 non-null   int64
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64
 8   Mother's qualification                          4424 non-null   int64
 9   Father's qualification                          4424 non-null   int64
 10  Mother's occupation                             4424 non-null   int64
 11  Father's occupation                             4424 non-null   int64
 12  Admission grade                                 4424 non-null   float64
 13  Displaced                                       4424 non-null   int64
 14  Educational special needs                       4424 non-null   int64
 15  Debtor                                          4424 non-null   int64
 16  Tuition fees up to date                         4424 non-null   int64
 17  Gender                                          4424 non-null   int64
 18  Scholarship holder                              4424 non-null   int64
 19  Age at enrollment                               4424 non-null   int64
 20  International                                   4424 non-null   int64
 21  Curricular units 1st sem (credited)             4424 non-null   int64
 22  Curricular units 1st sem (enrolled)             4424 non-null   int64
 23  Curricular units 1st sem (evaluations)          4424 non-null   int64
 24  Curricular units 1st sem (approved)             4424 non-null   int64
 25  Curricular units 1st sem (grade)                4424 non-null   float64
 26  Curricular units 1st sem (without evaluations)  4424 non-null   int64
 27  Curricular units 2nd sem (credited)             4424 non-null   int64
 28  Curricular units 2nd sem (enrolled)             4424 non-null   int64
 29  Curricular units 2nd sem (evaluations)          4424 non-null   int64
 30  Curricular units 2nd sem (approved)             4424 non-null   int64
 31  Curricular units 2nd sem (grade)                4424 non-null   float64
 32  Curricular units 2nd sem (without evaluations)  4424 non-null   int64
 33  Unemployment rate                               4424 non-null   float64
 34  Inflation rate                                  4424 non-null   float64
 35  GDP                                             4424 non-null   float64
dtypes: float64(7), int64(29)
memory usage: 1.2 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Target  4424 non-null   object
dtypes: object(1)
memory usage: 34.7+ KB

In [8]:
#Pretty print metadata
metadata = predict_students_dropout.metadata

pprint.pp(metadata)

{'uci_id': 697,
 'name': "Predict Students' Dropout and Academic Success",
 'repository_url': 'https://archive.ics.uci.edu/dataset/697/predict+students+dropout+and+academic+success',
 'data_url': 'https://archive.ics.uci.edu/static/public/697/data.csv',
 'abstract': 'A dataset created from a higher education institution (acquired '
             'from several disjoint databases) related to students enrolled in '
             'different undergraduate degrees, such as agronomy, design, '
             'education, nursing, journalism, management, social service, and '
             'technologies.\n'
             'The dataset includes information known at the time of student '
             'enrollment (academic path, demographics, and social-economic '
             "factors) and the students' academic performance at the end of "
             'the first and second semesters. \n'
             'The data is used to build classification models to predict '
             "students' dropout and academic sucess. The problem is formulated "
             'as a three category classification task, in which there is a '
             'strong imbalance towards one of the classes.',
 'area': 'Social Science',
 'tasks': ['Classification'],
 'characteristics': ['Tabular'],
 'num_instances': 4424,
 'num_features': 36,
 'feature_types': ['Real', 'Categorical', 'Integer'],
 'demographics': ['Marital Status',
                  'Education Level',
                  'Nationality',
                  'Occupation',
                  'Gender',
                  'Age'],
 'target_col': ['Target'],
 'index_col': None,
 'has_missing_values': 'no',
 'missing_values_symbol': None,
 'year_of_dataset_creation': 2021,
 'last_updated': 'Mon Feb 26 2024',
 'dataset_doi': '10.24432/C5MC89',
 'creators': ['Valentim Realinho',
              'Mónica Vieira Martins',
              'Jorge Machado',
              'Luís Baptista'],
 'intro_paper': {'title': "Early prediction of student's performance in higher "
                          'education: a case study',
                 'authors': 'Mónica V. Martins, Daniel Tolledo, Jorge Machado, '
                            'Luís M. T. Baptista, and Valentim Realinho',
                 'published_in': 'Trends and Applications in Information '
                                 'Systems and Technologies',
                 'year': 2021,
                 'url': 'http://www.worldcist.org/2021/',
                 'doi': 'http://www.doi.org/10.1007/978-3-030-72657-7_16'},
 'additional_info': {'summary': None,
                     'purpose': 'The dataset was created in a project that '
                                'aims to contribute to the reduction of '
                                'academic dropout and failure in higher '
                                'education, by using machine learning '
                                'techniques to identify students at risk at an '
                                'early stage of their academic path, so that '
                                'strategies to support them can be put into '
                                'place. \n'
                                '\n'
                                'The dataset includes information known at the '
                                'time of student enrollment – academic path, '
                                'demographics, and social-economic factors. \n'
                                '\n'
                                'The problem is formulated as a three category '
                                'classification task (dropout, enrolled, and '
                                'graduate) at the end of the normal duration '
                                'of the course. \n',
                     'funded_by': 'This dataset is supported by program SATDAP '
                                  '- Capacitação da Administração Pública '
                                  'under grant POCI-05-5762-FSE-000191, '
                                  'Portugal.',
                     'instances_represent': 'Each instance is a student',
                     'recommended_data_splits': 'The dataset was used, in our '
                                                'project, with a data split of '
                                                '80% for training and 20% for '
                                                'test.',
                     'sensitive_data': None,
                     'preprocessing_description': 'We performed a rigorous '
                                                  'data preprocessing to '
                                                  'handle data from anomalies, '
                                                  'unexplainable outliers, and '
                                                  'missing values.',
                     'variable_info': None,
                     'citation': 'If you use this dataset in experiments for a '
                                 'scientific publication, please kindly cite '
                                 'our paper: \n'
                                 'M.V.Martins, D. Tolledo, J. Machado, L. M.T. '
                                 'Baptista, V.Realinho. (2021) "Early '
                                 'prediction of student’s performance in '
                                 'higher education: a case study" Trends and '
                                 'Applications in Information Systems and '
                                 'Technologies, vol.1, in Advances in '
                                 'Intelligent Systems and Computing series. '
                                 'Springer. DOI: 10.1007/978-3-030-72657-7_16'}}

In [9]:
# Variable information
variables = predict_students_dropout.variables

print(variables.description)

0     1 – single 2 – married 3 – widower 4 – divorce...
1     1 - 1st phase - general contingent 2 - Ordinan...
2     Application order (between 0 - first choice; a...
3     33 - Biofuel Production Technologies 171 - Ani...
4                               1 – daytime 0 - evening
5     1 - Secondary education 2 - Higher education -...
6     Grade of previous qualification (between 0 and...
7     1 - Portuguese; 2 - German; 6 - Spanish; 11 - ...
8     1 - Secondary Education - 12th Year of Schooli...
9     1 - Secondary Education - 12th Year of Schooli...
10    0 - Student 1 - Representatives of the Legisla...
11    0 - Student 1 - Representatives of the Legisla...
12                  Admission grade (between 0 and 200)
13                                       1 – yes 0 – no
14                                       1 – yes 0 – no
15                                       1 – yes 0 – no
16                                       1 – yes 0 – no
17                                  1 – male 0 – female
18                                       1 – yes 0 – no
19                         Age of studend at enrollment
20                                       1 – yes 0 – no
21    Number of curricular units credited in the 1st...
22    Number of curricular units enrolled in the 1st...
23    Number of evaluations to curricular units in t...
24    Number of curricular units approved in the 1st...
25    Grade average in the 1st semester (between 0 a...
26    Number of curricular units without evalutions ...
27    Number of curricular units credited in the 2nd...
28    Number of curricular units enrolled in the 2nd...
29    Number of evaluations to curricular units in t...
30    Number of curricular units approved in the 2nd...
31    Grade average in the 2nd semester (between 0 a...
32    Number of curricular units without evalutions ...
33                                Unemployment rate (%)
34                                   Inflation rate (%)
35                                                  GDP
36    Target. The problem is formulated as a three c...
Name: description, dtype: object

In [10]:
# Combine features and target into a single DataFrame
try:
    df = pd.concat([X, y], axis=1)
    print("Features and target combined successfully.")
except Exception as e:
    print(f"Error combining features and target: {e}")
    raise

# Ensure ./data directory exists
try:
    os.makedirs('data', exist_ok=True)
    print("./data directory exists or created successfully.")
except Exception as e:
    print(f"Error creating directory: {e}")
    raise

# Save combined DataFrame to CSV
try:
    df.to_csv('data/row_data.csv', index=False)
    print("Combined data saved successfully.")
except Exception as e:
    print(f"Error saving combined data to CSV: {e}")
    raise

# Read the CSV back into a DataFrame
try:
    df_from_csv = pd.read_csv('data/row_data.csv')
    print("Data loaded successfully from CSV.")
except Exception as e:
    print(f"Error reading CSV into DataFrame: {e}")
    raise

Features and target combined successfully.
./data directory exists or created successfully.
Combined data saved successfully.
Data loaded successfully from CSV.

In [11]:
# Initial inspection
print(df.head())
#print(df.info())

   Marital Status  Application mode  Application order  Course  \
0               1                17                  5     171
1               1                15                  1    9254
2               1                 1                  5    9070
3               1                17                  2    9773
4               2                39                  1    8014

   Daytime/evening attendance  Previous qualification  \
0                           1                       1
1                           1                       1
2                           1                       1
3                           1                       1
4                           0                       1

   Previous qualification (grade)  Nacionality  Mother's qualification  \
0                           122.0            1                      19
1                           160.0            1                       1
2                           122.0            1                      37
3                           122.0            1                      38
4                           100.0            1                      37

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0
1                       3  ...                                    0
2                      37  ...                                    0
3                      37  ...                                    0
4                      38  ...                                    0

   Curricular units 2nd sem (enrolled)  \
0                                    0
1                                    6
2                                    6
3                                    6
4                                    6

   Curricular units 2nd sem (evaluations)  \
0                                       0
1                                       6
2                                       0
3                                      10
4                                       6

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                          0.000000
1                                    6                         13.666667
2                                    0                          0.000000
3                                    5                         12.400000
4                                    6                         13.000000

   Curricular units 2nd sem (without evaluations)  Unemployment rate  \
0                                               0               10.8
1                                               0               13.9
2                                               0               10.8
3                                               0                9.4
4                                               0               13.9

   Inflation rate   GDP    Target
0             1.4  1.74   Dropout
1            -0.3  0.79  Graduate
2             1.4  1.74   Dropout
3            -0.8 -3.12  Graduate
4            -0.3  0.79  Graduate

[5 rows x 37 columns]

In [12]:
df.columns

Index(['Marital Status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance', 'Previous qualification',
       'Previous qualification (grade)', 'Nacionality',
       'Mother's qualification', 'Father's qualification',
       'Mother's occupation', 'Father's occupation', 'Admission grade',
       'Displaced', 'Educational special needs', 'Debtor',
       'Tuition fees up to date', 'Gender', 'Scholarship holder',
       'Age at enrollment', 'International',
       'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)',
       'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)',
       'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)',
       'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)',
       'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)',
       'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without evaluations)', 'Unemployment rate',
       'Inflation rate', 'GDP', 'Target'],
      dtype='object')

## Summery 

In this notebook, we successfully:
1. Fetched the raw dataset from the UCI repository using the `fetch_ucirepo` function.
2. Extracted the features and target variables into separate dataframes.
3. Combined the features and target into a single dataframe for easier analysis.
4. Performed an initial inspection of the combined data to understand its structure.
5. Ensured the existence of the necessary directories and saved the combined data to a CSV file.
6. Reloaded the data from the CSV file to verify the save operation.

By organising and saving the raw data in a structured manner, we have laid a solid foundation for subsequent steps in the data analysis and machine learning workflow. The next steps will involve exploratory data analysis (EDA), data cleaning, and eventually building and evaluating machine learning models.

Proceed to the next notebook to start with exploratory data analysis (EDA). [Predict_Students_Dropout_EDA_02](./Predict_Students_Dropout_EDA_02.ipynb)